version: "3.9"

services:
  db:
    image: postgres:15
    container_name: lms_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lms_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_app
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
    networks:
      - lms_net

volumes:
  postgres_data:

networks:
  lms_net:
